### ISSUE TITLE
Replace MD5 hashing with safer alternative

### ISSUE THREAD

**Issue by Spaggel** [Ozencb/library-management-system#1]
Hi,

I've noticed you're using md5 hashing for passwords which is not very safe. 
You might want to look at [password_hash](https://www.php.net/manual/en/function.password-hash.php) functions. 
If you implement the `password_hash` functions, please use `password_verify` instead of `==` to check for valid passwords.  Using `==` is not safe because it doesn't compare types and might lead to invalid passwords being seen as valid passwords.
[This](https://www.cryptologie.net/article/268/how-to-compare-password-hashes-in-php/) post (not written by me) has some great examples.

Good luck!

**Comment by Ozencb** [comment]
Some of the features, including MD5, were used purely because they were requirements for the project that our professor has set. I know that MD5 hashes can easily be decrypted but, well... 

```==``` not being safe is very interesting though, seems like a very important thing to keep in mind. I know for a fact that most of my classmates used something like this for their login pages. I will definitely read the post.

Thank you so much for the feedback!
